PrayashStore/Models/Product.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PrayashStore.Models
{
    public class Product
    {
        public Product()
        {
            ProductImages = new List<ProductImage>();
        }

        public int Id { get; set; }

        [StringLength(255)]
        [Required]
        public string Name { get; set; }

        [StringLength(255)]
        public string Description { get; set; }

        public decimal Price { get; set; }

        [Required]
        public Gender Gender { get; set; }

        [Required]
        public int CategoryId { get; set; }
        public Category Category { get; set; }

        public byte[] Thumbnail { get; set; }

        public ICollection<ProductImage> ProductImages { get; set; }
    }
}

PrayashStore/Controllers/ImageController.cs
using PrayashStore.Services.Interfaces;
using System.Web;
using System.Web.Mvc;

namespace PrayashStore.Controllers
{
    public class ImageController : Controller
    {
        private readonly IProductService _productService;
        private readonly IProductImageService _productImageService;

        public ImageController(IProductService productService, IProductImageService productImageService)
        {
            _productService = productService;
            _productImageService = productImageService;
        }

        public ActionResult GetProductThumbnail(int id)
        {
            var product = _productService.GetProductById(id);
            return File(product.Thumbnail, "image/png");
        }

        public ActionResult GetProductImage(int id)
        {
            var productImage = _productImageService.GetProductImageById(id);
            return File(productImage.ImageData, "image/png");
        }

        [HttpPost]
        public ActionResult AddProductImage(int productId, HttpPostedFileBase image)
        {
            if (image == null)
                return Json(new { success = false, message = "Image not found, Upload Failed" });

            var product = _productService.GetProductById(productId);
            if (product == null)
                return Json(new { success = false, message = "Product not found, Upload failed" });

            _productImageService.AddProductImage(product, image);
            return Json(new { success = true, message = "Image Uploaded Successfully" });
        }

        [HttpPost]
        public ActionResult DeleteProductImage(int id)
        {
            var productImage = _productImageService.GetProductImageById(id);
            if (productImage == null)
                return Json(new { success = false, message = "Image not found, Cannot Remove" });

            _productImageService.RemoveProductImage(productImage);
            return Json(new { success = true, message = "Image Removed Successfully" });
        }
    }
}

PrayashStore/Controllers/ProductController.cs
using AutoMapper;
using PrayashStore.Constants;
using PrayashStore.Extensions;
using PrayashStore.Models;
using PrayashStore.Services.Interfaces;
using PrayashStore.ViewModels;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace PrayashStore.Controllers
{
    [Authorize(Roles = "CanManageProducts,Admin")]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly ICartService _cartService;
        private readonly IProductImageService _productImageService;

        public ProductController(IProductService productService, ICategoryService categoryService,
            ICartService cartService, IProductImageService productImageService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _cartService = cartService;
            _productImageService = productImageService;
        }
        public ActionResult Index(string categoryName, string gender)
        {
            ViewBag.Categories = _categoryService.GetAllCategories().Select(x => x.Name).ToList();
            ViewBag.Genders = Enum.GetNames(typeof(Gender));

            var products = new List<Product>();

            if (string.IsNullOrWhiteSpace(categoryName) && string.IsNullOrWhiteSpace(gender))
            {
                products = _productService.GetAllProducts().ToList();
                return View(products);
            }

            if (!string.IsNullOrWhiteSpace(categoryName) && !string.IsNullOrWhiteSpace(gender))
            {
                products = _productService.GetAllProductsByCategoryNameAndGender(categoryName, gender).ToList();
                return View(products);
            }

            if (string.IsNullOrWhiteSpace(categoryName))
            {
                products = _productService.GetAllProductsByGender(gender).ToList();
                return View(products);
            }

            if (string.IsNullOrWhiteSpace(gender))
            {
                products = _productService.GetAllProductsByCategoryName(categoryName).ToList();
                return View(products);
            }

            return View(products);
        }

        public ActionResult Create()
        {
            var productAddFormViewModel = new ProductAddFormViewModel
            {
                Categories = _categoryService.GetAllCategories()
            };
            return View(productAddFormViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductAddFormViewModel productAddFormViewModel)
        {

            if (!ModelState.IsValid)
            {
                productAddFormViewModel.Categories = _categoryService.GetAllCategories();
                return View(productAddFormViewModel);
            }

            var product = Mapper.Map<Product>(productAddFormViewModel);

            if (productAddFormViewModel.Thumbnail != null)
            {
                product.Thumbnail = ProcessImage("thumbnail", productAddFormViewModel.Thumbnail.InputStream,
                                                    ImageSizeConstant.ProductThumbnailHeight, ImageSizeConstant.ProductThumbnailWidth);
            }


            if (productAddFormViewModel.Images != null)
            {
                var imageList = new List<ProductImage>();
                foreach (var image in productAddFormViewModel.Images)
                {
                    if (image != null)
                    {
                        var productImage = new ProductImage
                        {
                            ProductId = product.Id,
                            ImageData = ProcessImage("image", image.InputStream,
                                                        ImageSizeConstant.ProductImageHeight, ImageSizeConstant.ProductImageWidth)
                        };

                        imageList.Add(productImage);
                    }
                }
                product.ProductImages = imageList;
            }
            _productService.AddProduct(product);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var product = _productService.GetProductById(id.GetValueOrDefault());
            if (product == null)
                return HttpNotFound();

            var productEditFormViewModel = Mapper.Map<ProductEditFormViewModel>(product);
            productEditFormViewModel.Categories = _categoryService.GetAllCategories();
            productEditFormViewModel.ProductImages = _productImageService.GetAllImagesByProductId(id.GetValueOrDefault());

            return View(productEditFormViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductEditFormViewModel productEditFormViewModel)
        {
            var originalProduct = _productService.GetProductById(productEditFormViewModel.Id);
            if (!ModelState.IsValid || originalProduct == null)
            {
                productEditFormViewModel.ProductImages = _productImageService.GetAllImagesByProductId(productEditFormViewModel.Id);
                productEditFormViewModel.Categories = _categoryService.GetAllCategories();
                return View(productEditFormViewModel);
            }

            var product = Mapper.Map<Product>(productEditFormViewModel);

            if (productEditFormViewModel.Thumbnail != null)
            {
                product.Thumbnail = ProcessImage("thumbnail", productEditFormViewModel.Thumbnail.InputStream,
                                                    ImageSizeConstant.ProductThumbnailHeight, ImageSizeConstant.ProductThumbnailWidth);
            }
            else
            {
                product.Thumbnail = originalProduct.Thumbnail;
            }

            _productService.EditProduct(product);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var product = _productService.GetProductWithCategory(id.GetValueOrDefault());
            if (product == null)
                return HttpNotFound();

            var productDetailViewModel = Mapper.Map<ProductDetailViewModel>(product);
            return View(productDetailViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            if (!ModelState.IsValid)
                return View();

            var product = _productService.GetProductById(id);
            _productService.RemoveProduct(product);
            return RedirectToAction("Index");
        }

        private byte[] ProcessImage(string imageType, Stream imageStream, int height = 250, int width = 250)
        {
            using (Image img = Image.FromStream(imageStream))
            {
                var data = img.Resize(width, height)
                                .ToByteArray(ImageFormat.Png);
                return data;
            }

        }

    }
}

PrayashStore/Views/Product/Delete.cshtml
@model PrayashStore.ViewModels.ProductDetailViewModel

@{
    ViewBag.Title = "Delete Product";
}

<h3>Are you sure you want to delete this product?</h3>
<br />


<div class="container-fluid col-left-no-padding col-right-no-padding">
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="form-horizontal">
                <div class="col-md-12">
                    <div class="form-group">    
                        <br />              
                    </div>
                </div>
            </div>
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-sm-2 ">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", disabled = "disabled" })
                    </div>
                 </div>
            </div>
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-sm-2 ">
                        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(model => model.Price, new { @class = "form-control", disabled = "disabled" })
                    </div>
                </div>
            </div>
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-sm-2 ">
                        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(model => model.Gender, new { @class = "form-control", disabled = "disabled" })
                    </div>
                </div>
            </div>
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-sm-2 ">
                        @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(model => model.Category.Name, new { @class = "form-control", disabled = "disabled" })
                    </div>
                </div>
            </div>
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-sm-2 ">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-sm-10">
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control vertical-resize", disabled = "disabled" })
                    </div>
                </div>
            </div>
        </div>         
        <div class="col-md-4 col-xs-12 col-md-offset-2">
            <div class="row">
                <div class="col-md-12">
                    <div class="img-crop">
                        <img src="@Url.Action("GetProductThumbnail", "Image", new { id = Model.Id })" alt="..." class="img-responsive" />
                    </div>
                </div>
            </div>
        </div>               
    </div>
</div>

@using (Html.BeginForm("Delete", "Product"))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>    
}

<div class="form-group">
    @Html.ActionLink("Cancel and Go Back", "Index")
</div>

PrayashStore/Views/Product/Edit.cshtml
@model PrayashStore.ViewModels.ProductEditFormViewModel
@{
    ViewBag.Title = "Edit Product";
}

<h3>@ViewBag.Title</h3>
<br />

@using (Html.BeginForm("Edit", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(x => x.Id)

    <div class="form-group">
        @Html.LabelFor(x => x.Name)
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Description)
        @Html.TextAreaFor(x => x.Description, new { @class = "form-control vertical-resize" })
        @Html.ValidationMessageFor(x => x.Description, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Price)
        @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Price, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Gender)
        @Html.EnumDropDownListFor(x => x.Gender, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Gender, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Category)
        @Html.DropDownListFor(x => x.Category, Model.Categories.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }), "", new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Category, "", new { @class = "text-danger" })
    </div>
 
    <div class="form-group">
        <div class="container-fluid col-left-no-padding col-right-no-padding">
            <div class="row">
                <div class="col-md-12">
                    @Html.LabelFor(x => x.Thumbnail)
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div id="thumbnail-section">
                        <div id="load-thumbnail" class="img-crop">
                            <img id="thumbnail-id" src="@Url.Action("GetProductThumbnail", "Image", new { id = Model.Id })" alt="..." class="img-responsive" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div id="thumbnail-browse-section" class="form-group">
                        <input type="file" name="thumbnail" id="thumbnail-file" class="file hide-element">
                        <div class="input-group">
                            <span class="input-group-btn">
                                <button class="browse btn btn-primary" type="button"><i class="fa fa-search"></i> Browse</button>
                            </span>
                            <input type="text" id="thumbnail-name" class="form-control" disabled placeholder="Upload Image" style="padding-left:5px;">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button" id="cancel-thumbnail-chg"><i class="fa fa-remove"></i> Cancel</button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="alert alert-info" role="alert">            
            <a href="#" data-toggle="modal" data-id="@Model" data-target="#editImagesModal" class="alert-link">Click Here </a> to Edit Product Images.
        </div>        
    </div>

    <br />

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
    <div class="form-group">
        @Html.ActionLink("Cancel and Go Back", "Index")
    </div>
}

<div class="modal fade" id="editImagesModal" tabindex="-1" role="dialog" aria-labelledby="editImagesModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="editImagesModalTitle">Edit Product Images</h4>
            </div>
            <div class="modal-body">
                <div class="container-fluid" id="images-section">
                    <div id="image-modal-body-content">
                        <div class="form-group">
                            <button type="button" class="btn btn-primary" id="add-image-btn">
                                <i class="fa fa-plus"></i> Add New Image
                            </button>
                        </div>
                        <div id="image-browse-section" class="form-group" style="display:none">
                            <input type="file" name="product-image" id="image-file" class="file hide-element">
                            <div class="input-group">
                                <span class="input-group-btn">
                                    <button class="browse btn btn-primary" type="button"><i class="fa fa-search"></i>Browse</button>
                                </span>
                                <input type="text" id="image-name" class="form-control" disabled placeholder="Upload Image" style="padding-left:5px;">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" type="button" id="add-image" data-product-id="@Model.Id"><i class="fa fa-plus"></i> Add</button>
                                    <button class="btn btn-default" type="button" id="cancel-image-add"><i class="fa fa-remove"></i> Cancel</button>
                                </span>
                            </div>
                        </div>

                        <div class="row" id="image-row">
                            @foreach (var image in Model.ProductImages)
                            {
                                <div class="col-sm-6 col-md-3" id="id-@image.Id">
                                    <div class="thumbnail img-crop">
                                        <img src="@Url.Action("GetProductImage", "Image", new { id = image.Id })" alt="..." class="img-responsive" />
                                    </div>

                                    <div class="caption">
                                        <p>
                                            <button type="button" class="add-to-cart btn btn-default btn-block" id="remove-image" data-image-id="@image.Id">
                                                <i class="fa fa-trash" aria-hidden="true"></i> Remove
                                            </button>
                                        </p>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $(document).on('click', '.browse', function () {
                var file = $(this).parent().parent().parent().find('.file');
                file.trigger('click');
            });

            $(document).on('change', '#thumbnail-file', function () {
                $(this).parent().find('#thumbnail-name').val($(this).val().replace(/C:\\fakepath\\/i, ''));
            });

            $('body').on('change', '#thumbnail-file', function () {
                readURL(this);
            });

            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#thumbnail-id').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(input.files[0]);
                }
            }

            $('body').on('click', '#cancel-thumbnail-chg', function (event) {
                event.preventDefault();
                $('#thumbnail-section').load(GetUrlPath() + ' #load-thumbnail');
                $("#thumbnail-browse-section").load(GetUrlPath() + ' #thumbnail-browse-section');
            });

            //Get URL path for the page
            function GetUrlPath() {
                var urlArray = window.location.href.split("/");
                var urlPath = '/';
                for (var i = 3; i < urlArray.length; i++) {
                    urlPath = urlPath + urlArray[i] + '/';
                }
                return urlPath;
            }

            // Show elements when Add button is clicked
            $('body').on('click', '#add-image-btn', function (event) {
                event.preventDefault();                
                $('#image-browse-section').show();
            });

            // Hide elements when Cancel button is clicked
            $('body').on('click', '#cancel-image-add', function (event) {
                event.preventDefault();
                $('#image-browse-section').hide();
                $('#image-file').val('');
                $('#image-name').val('');
            });

            // Update textbox value with image name
            $(document).on('change', '#image-file', function () {
                $(this).parent().find('#image-name').val($(this).val().replace(/C:\\fakepath\\/i, ''));
            });

            // Remove Image
            $('body').on('click', '#remove-image', function (event) {
                event.preventDefault();
                var imageId = $(this).attr('data-image-id');

                // Checking whether FormData is available in browser
                if (window.FormData !== undefined) {
                    var imageCount = $("#image-row").children().length;
                    if (imageCount > 1) {
                        $.ajax({
                            url: '@Url.Action("DeleteProductImage", "Image")',
                            type: "POST",
                            data: { 'id': imageId },
                            dataType: 'json',
                            success: function (result) {
                                if (!result.success) {                                    
                                    ShowToast(result.message, 2500, 'error');
                                }
                                else {
                                    $('#images-section').load(GetUrlPath() + ' #image-modal-body-content');
                                }
                            },
                            error: function (XMLHttpRequest, textStatus, errorThrown) {
                                console.log("Status: " + textStatus + ", Error: " + errorThrown);
                                ShowToast("Error: Image could not be removed", 2500, 'error');

                            }
                        });
                    }
                    else {
                        ShowToast("Error: Image could not be removed", 2500, 'error');
                    }
                }
                else {
                    ShowToast("Error: FormData is not supported.", 2500, 'error');
                }

            });

            $('body').on('click', '#add-image', function (event) {
                event.preventDefault();
                var productId = $(this).attr('data-product-id');

                // Checking whether FormData is available in browser
                if (window.FormData !== undefined) {
                    var files = $('#image-file').get(0).files;
                    var fileData = new FormData();

                    // Looping over all files and add it to FormData object
                    for (var i = 0; i < files.length; i++) {
                        fileData.append("image", files[i]);
                    }

                    // Adding one more key to FormData object
                    fileData.append('productId', productId);

                    $.ajax({
                        url: '@Url.Action("AddProductImage", "Image")',
                        type: "POST",
                        contentType: false, // Not to set any content header
                        processData: false, // Not to process data
                        data: fileData,
                        dataType: 'json',
                        success: function (result) {
                            if (!result.success) {                                
                                ShowToast(result.message, 2500, 'error');
                            }
                            else {
                                $('#images-section').load(GetUrlPath() + ' #image-modal-body-content');
                            }
                        },
                        error: function (XMLHttpRequest, textStatus, errorThrown) { 
                            console.log("Status: " + textStatus + ", Error: " + errorThrown);
                            ShowToast("Error: Image Add failed", 2500, 'error');

                        }
                    });
                }
                else {                    
                    ShowToast("Error: FormData is not supported.", 2500, 'error');
                }
            });
        });
    </script>
}

PrayashStore/Views/Product/Index.cshtml
@model IEnumerable<PrayashStore.Models.Product>

@{
    ViewBag.Title = "Manage Products";
}

<h3>@ViewBag.Title</h3>
<br />

<p>
    <a href="@Url.Action("Create")" class="btn btn-primary">
        <i class="fa fa-plus-circle"></i> Add New Product
    </a>
</p>

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="form-group">
                @Html.Label("Category:", htmlAttributes: new { @class = "control-label" })
                @Html.DropDownList("categoryName", new SelectList(ViewBag.Categories), "All", new { @class = "form-control ", id = "category-list" })
            </div>
        </div>
        <div class="col-md-6 col-xs-12">
            <div class="form-group">
                @Html.Label("Gender:", htmlAttributes: new { @class = "control-label" })
                @Html.DropDownList("gender", new SelectList(ViewBag.Genders), "All", new { @class = "form-control ", id = "gender-list" })
            </div>
        </div>
    </div>
}


@if (Model.Count() == 0)
{
    <div class="row">
        <div class="col-xs-12">
            <div class="alert alert-info" role="alert">Product not found.</div>
        </div>
     </div>    
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-6 col-md-3">
            <div class="thumbnail img-crop">                
                <img src="@Url.Action("GetProductThumbnail", "Image", new { id = item.Id })" alt="..." class="img-responsive" />
            </div>

            <div class="caption">
                <p>@Html.DisplayFor(modelItem => item.Name) (@Html.DisplayFor(modelItem => item.Gender))<br />$ @Html.DisplayFor(modelItem => item.Price)</p>
                <p>
                    <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-primary">
                        <i class="fa fa-pencil"></i> Edit
                    </a>
                    <a href="@Url.Action("Delete", new { id = item.Id })" class="btn btn-default">
                        <i class="fa fa-trash"></i> Delete
                    </a>
                </p>
            </div>
        </div>
    }
</div>

@section scripts
{
    <script>
        $(document).ready(function () {
            // Submit form when dropdown value is changed.
            $('#category-list').on('change', function (event) {
                var form = $(event.target).parents('form');
                form.submit();
            });
            $('#gender-list').on('change', function (event) {
                var form = $(event.target).parents('form');
                form.submit();
            });
        });
    </script>
}